.cran_packages <- c("tidyverse", "cowplot", "picante", "vegan", "HMP", "dendextend", "rms", "devtools")
.bioc_packages <- c("phyloseq", "DESeq2", "microbiome", "metagenomeSeq", "ALDEx2")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
  install.packages(.cran_packages[!.inst])
}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(.bioc_packages)
BiocManager::install("rms")
devtools::install_github("adw96/breakaway")
devtools::install_github(repo = "UVic-omics/selbal")

library(tidyverse); packageVersion("tidyverse")                 
library(phyloseq); packageVersion("phyloseq")                    
library(DESeq2); packageVersion("DESeq2")                        
library(microbiome); packageVersion("microbiome")               
library(vegan); packageVersion("vegan")                          
library(picante); packageVersion("picante")                       
library(ALDEx2); packageVersion("ALDEx2")                        
library(metagenomeSeq); packageVersion("metagenomeSeq")          
library(HMP); packageVersion("HMP")                              
library(dendextend); packageVersion("dendextend") 
devtools::install_github(repo = "malucalle/selbal")
library(selbal); packageVersion("selbal")                          
library(rms); packageVersion("rms")
library(breakaway); packageVersion("breakaway")   

(ps <- readRDS("~/Desktop/Bioinformatica/Afstuderen/Naturalis/arise-soil-pilot-analysis/data/location1OTU.csv"))

